api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources'
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/vendor/titi60/sylius-extra-api-plugin/src/Resources/config/api_platform'

sylius_product:
  resources:
    product:
      classes:
        repository: 'DavidRoberto\SyliusExtraApiPlugin\Repository\ProductRepository'

sylius_payment:
  resources:
    payment:
      classes:
        repository: 'DavidRoberto\SyliusExtraApiPlugin\Repository\PaymentRepository'

framework:
  serializer:
    mapping:
      paths:
        - '%kernel.project_dir%/vendor/titi60/sylius-extra-api-plugin/src/Resources/config/serializer'
