sylius_product:
  resources:
    product:
      classes:
        repository: 'DavidRoberto\SyliusExtraApiPlugin\Repository\ProductRepository'

sylius_payment:
  resources:
    payment:
      classes:
        repository: 'DavidRoberto\SyliusExtraApiPlugin\Repository\PaymentRepository'
